play.http.secret.key = "changeme-in-production"
play.evolutions.enabled = false
play.ws.ssl.loose.acceptAnyCertificate = true
play.i18n.langs = ["en"]
play.modules.enabled += "be.objectify.deadbolt.scala.DeadboltModule"
play.modules.enabled += "modules.CustomDeadboltHook"
play.modules.enabled += "modules.StartupModule"

# Lynx Reporting
lynx.reporting.base_url = "http://easiersolar.com/api/revenue"
lynx.reporting.token = "###"

# MongoDB
mongodb.host = "localhost"
mongodb.port = 27017
mongodb.db = "advanced"

# Redis
redis.host = "localhost"
redis.port = 6379

# Google Auth
google_auth.client_id = "CLIENT_ID"
google_auth.client_secret = "SECRET"
google_auth.application_name = "adVanced"
google_auth.redirect_uri = "tapatlas.com"
google_auth.timeout_seconds = 30

# Facebook
facebook.graph.baseUrl = "https://graph.facebook.com/v2.8/"
facebook.graph.requestTimeout = 15

# MySQL (Slick)
slick.dbs.default.db.driver = "com.mysql.cj.jdbc.Driver"
slick.dbs.default.db.url = "jdbc:mysql://ciii-mysql.copdec0azp7r.us-west-2.rds.amazonaws.com:3306/reporting"
slick.dbs.default.db.user = "username"
slick.dbs.default.db.password = "password"
slick.dbs.default.db.connectionTimeout = 30s
slick.dbs.default.db.numThreads = 12
slick.dbs.default.profile = "slick.jdbc.MySQLProfile$"

# Application Settings
defaultMySQLTimeout = 15
password_salt = "SALT"
admin_email = "developncode@gmail.com"
password_reset_mandrill_template = "adVanced-password-reset"
chart_init_timeout_s = 30
