package models.mongodb.lynx

import Shared.Shared._
import com.mongodb.casbah.Imports._
import models.mysql._
import org.joda.time.DateTime
import org.joda.time.format.DateTimeFormat
import org.joda.time.format.DateTimeFormatter

object TQReporting {
  val dtf: DateTimeFormatter = DateTimeFormat.forPattern("yyyy-MM-dd")
  def arrivalFactCollection = advancedCollection("tq_reporting_arrival_facts")

  def arrivalFactToDBObject(arrivalFact: ArrivalFact): DBObject = {
    DBObject(
      "id" -> arrivalFact.id,
      "ab_tests" -> arrivalFact.session.ab_tests,
      "adgroupid" -> arrivalFact.traffic_source.adgroupid,
      "git_hash" -> arrivalFact.session.git_hash,
      "arrivals" -> arrivalFact.browser.arrivals,
      "browser" -> arrivalFact.browser.browser,
      "browser_id" -> arrivalFact.browser.browser_id,
      "browser_version" -> arrivalFact.browser.browser_version,
      "bounce" -> arrivalFact.browser.bounce,
      "conf" -> arrivalFact.traffic_source.conf,
      "conu" -> arrivalFact.traffic_source.conu,
      "conversion" -> arrivalFact.traffic_source.conversion,
      "conversion_count" -> arrivalFact.traffic_source.conversion_count,
      "conversion_page" -> arrivalFact.traffic_source.conversion_page,
      "created_at" -> dtOptToStrOpt(arrivalFact.session.created_at),
      "day_of_week" -> arrivalFact.session.day_of_week,
      "device_brand" -> arrivalFact.device.device_brand,
      "device_model" -> arrivalFact.device.device_model,
      "duration" -> arrivalFact.session.duration,
      "device_name" -> arrivalFact.device.device_name,
      "device_type" -> arrivalFact.device.device_type,
      "electric_bill" -> arrivalFact.form.electric_bill,
      "email" -> arrivalFact.form.email,
      "entry_page" -> arrivalFact.session.entry_page,
      "entry_url" -> arrivalFact.session.entry_url,
      "exit_url" -> arrivalFact.session.exit_url,
      "event_category" -> arrivalFact.event_1.event_category,
      "events_count" -> arrivalFact.event_1.events_count,
      "form_city" -> arrivalFact.form.form_city,
      "form_state" -> arrivalFact.form.form_state,
      "form_zip" -> arrivalFact.form.form_zip,
      "gclid" -> arrivalFact.traffic_source.gclid,
      "ip_address" -> arrivalFact.session.ip_address,
      "ip_blacklisted" -> arrivalFact.session.ip_blacklisted,
      "is_ip_blacklisted" -> arrivalFact.session.is_ip_blacklisted,
      "lp_conv_u" -> arrivalFact.traffic_source.lp_conv_u,
      "last_activity" -> dtOptToStrOpt(arrivalFact.session.last_activity),
      "local_hour" -> arrivalFact.session.local_hour,
      "maxmind_zip" -> arrivalFact.session.maxmind_zip,
      "name_capture" -> arrivalFact.session.name_capture,
      "new_ip" -> arrivalFact.session.new_ip,
      "new_session" -> arrivalFact.session.new_session,
      "os_name" -> arrivalFact.session.os_name,
      "os_version" -> arrivalFact.session.os_version,
      "page_views" -> arrivalFact.session.page_views,
      "prop_own" -> arrivalFact.form.prop_own,
      "revenue" -> arrivalFact.session.revenue,
      "robot_id" -> arrivalFact.browser.robot_id,
      "user_agent" -> arrivalFact.browser.user_agent,
      "session_id" -> arrivalFact.session.session_id,
      "utm_source" -> arrivalFact.traffic_source.utm_source,
      "utm_campaign" -> arrivalFact.traffic_source.utm_campaign,
      "utm_medium" -> arrivalFact.traffic_source.utm_medium,
      "lp_ctc" -> arrivalFact.traffic_source.lp_ctc,
      "form_step_1" -> arrivalFact.event_1.form_step_1,
      "form_step_2" -> arrivalFact.event_1.form_step_2,
      "form_step_3" -> arrivalFact.event_1.form_step_3,
      "form_complete" -> arrivalFact.event_2.form_complete,
      "lp_content_engage" -> arrivalFact.event_2.lp_content_engage,
      "page_closed" -> arrivalFact.event_2.page_closed,
      "page_loaded" -> arrivalFact.event_2.page_loaded,
      "form_step_2b" -> arrivalFact.event_1.form_step_2b,
      "page_rendered" -> arrivalFact.event_1.page_rendered,
      "form_step_4" -> arrivalFact.event_1.form_step_4,
      "form_step_5" -> arrivalFact.event_2.form_step_5,
      "form_step_6" -> arrivalFact.event_2.form_step_6,
      "form_step_7" -> arrivalFact.event_2.form_step_7,
      "form_step_8" -> arrivalFact.event_2.form_step_8,
      "maxmind_failure_on_page_load" -> arrivalFact.event_1.maxmind_failure_on_page_load,
      "landing_page_completed" -> arrivalFact.event_1.landing_page_completed,
      "address_completed" -> arrivalFact.event_1.address_completed,
      "ownership_completed" -> arrivalFact.event_1.ownership_completed,
      "power_bill_completed" -> arrivalFact.event_1.power_bill_completed,
      "power_company_completed" -> arrivalFact.event_1.power_company_completed,
      "name_completed" -> arrivalFact.event_1.name_completed,
      "email_completed" -> arrivalFact.event_1.email_completed,
      "phone_completed" -> arrivalFact.event_1.phone_completed,
      "email_modal_completed" -> arrivalFact.event_1.email_modal_completed,
      "credit_score_completed" -> arrivalFact.event_1.credit_score_completed,
      "creative" -> arrivalFact.event_1.creative,
      "page_focus" -> arrivalFact.event_1.page_focus,
      "page_blur" -> arrivalFact.event_1.page_blur,
      "u_lp_ctc" -> arrivalFact.traffic_source.u_lp_ctc,
      "u_form_step_1" -> arrivalFact.u_event_1.u_form_step_1,
      "u_form_step_2" -> arrivalFact.u_event_1.u_form_step_2,
      "u_form_step_3" -> arrivalFact.u_event_1.u_form_step_3,
      "u_form_complete" -> arrivalFact.u_event_2.u_form_complete,
      "u_lp_content_engage" -> arrivalFact.traffic_source.u_lp_content_engage,
      "u_page_closed" -> arrivalFact.u_event_1.u_page_closed,
      "u_page_loaded" -> arrivalFact.u_event_1.u_page_loaded,
      "u_form_step_2b" -> arrivalFact.u_event_1.u_form_step_2b,
      "u_page_rendered" -> arrivalFact.u_event_1.u_page_rendered,
      "u_form_step_4" -> arrivalFact.u_event_1.u_form_step_4,
      "u_form_step_5" -> arrivalFact.u_event_1.u_form_step_5,
      "u_form_step_6" -> arrivalFact.u_event_2.u_form_step_6,
      "u_form_step_7" -> arrivalFact.u_event_2.u_form_step_7,
      "u_form_step_8" -> arrivalFact.u_event_2.u_form_step_8,
      "u_maxmind_failure_on_page_load" -> arrivalFact.u_event_1.u_maxmind_failure_on_page_load,
      "u_landing_page_completed" -> arrivalFact.u_event_1.u_landing_page_completed,
      "u_address_completed" -> arrivalFact.u_event_1.u_address_completed,
      "u_ownership_completed" -> arrivalFact.u_event_1.u_ownership_completed,
      "u_power_bill_completed" -> arrivalFact.u_event_1.u_power_bill_completed,
      "u_power_company_completed" -> arrivalFact.u_event_1.u_power_company_completed,
      "u_name_completed" -> arrivalFact.u_event_1.u_name_completed,
      "u_email_completed" -> arrivalFact.u_event_1.u_email_completed,
      "u_phone_completed" -> arrivalFact.u_event_1.u_phone_completed,
      "u_email_modal_completed" -> arrivalFact.u_event_1.u_email_modal_completed,
      "u_credit_score_completed" -> arrivalFact.u_event_1.u_credit_score_completed,
      "u_page_focus" -> arrivalFact.u_event_1.u_page_focus,
      "u_page_blur" -> arrivalFact.u_event_1.u_page_blur,
      "keyword" -> arrivalFact.traffic_source.keyword,
      "g_network" -> arrivalFact.traffic_source.g_network,
      "g_device" -> arrivalFact.traffic_source.g_device,
      "g_location" -> arrivalFact.traffic_source.g_location
    )
  }

  def dboToArrivalFact(dbo: DBObject): ArrivalFact =
    ArrivalFact(
      id = dbo.as[Option[Long]]("id"),
      traffic_source = ArrivalFactTrafficSource(
        adgroupid = dbo.as[Option[String]]("adgroupid"),
        gclid = dbo.as[Option[String]]("gclid"),
        lp_conv_u = dbo.as[Option[Int]]("lp_conv_u"),
        keyword = dbo.as[Option[String]]("keyword"),
        g_network = dbo.as[Option[String]]("g_network"),
        g_device = dbo.as[Option[String]]("g_device"),
        g_location = dbo.as[Option[String]]("g_location"),
        conf = dbo.as[Option[Int]]("conf"),
        conu = dbo.as[Option[Int]]("conu"),
        conversion = dbo.as[Option[Int]]("conversion"),
        conversion_count = dbo.as[Option[Int]]("conversion_count"),
        conversion_page = dbo.as[Option[String]]("conversion_page"),
        lp_ctc = dbo.as[Int]("lp_ctc"),
        u_lp_ctc = dbo.as[Int]("u_lp_ctc"),
        u_lp_content_engage = dbo.as[Int]("u_lp_content_engage"),
        utm_source = dbo.as[Option[String]]("utm_source"),
        utm_campaign = dbo.as[Option[String]]("utm_campaign"),
        utm_medium = dbo.as[Option[String]]("utm_medium")
      ),
      device = ArrivalFactDevice(
        device_name = dbo.as[Option[String]]("device_name"),
        device_type = dbo.as[Option[String]]("device_type"),
        device_brand = dbo.as[Option[String]]("device_brand"),
        device_model = dbo.as[Option[String]]("device_model")
      ),
      browser = ArrivalFactBrowser(
        browser = dbo.as[Option[String]]("browser"),
        browser_id = dbo.as[Option[String]]("browser_id"),
        browser_version = dbo.as[Option[String]]("browser_version"),
        arrivals = dbo.as[Int]("arrivals"),
        bounce = dbo.as[Int]("bounce"),
        robot_id = dbo.as[Option[String]]("robot_id"),
        user_agent = dbo.as[Option[String]]("user_agent")
      ),
      session = ArrivalFactSession(
        session_id = dbo.as[Option[Long]]("session_id"),
        ip_address = dbo.as[Option[String]]("ip_address"),
        ip_blacklisted = dbo.as[Option[Int]]("ip_blacklisted"),
        is_ip_blacklisted = dbo.as[Option[Int]]("is_ip_blacklisted"),
        maxmind_zip = dbo.as[Option[String]]("maxmind_zip"),
        name_capture = dbo.as[Int]("name_capture"),
        new_ip = dbo.as[Int]("new_ip"),
        new_session = dbo.as[Int]("new_session"),
        os_name = dbo.as[Option[String]]("os_name"),
        os_version = dbo.as[Option[String]]("os_version"),
        ab_tests = dbo.as[Option[String]]("ab_tests"),
        git_hash = dbo.as[Option[String]]("git_hash"),
        created_at = strOptToDtOpt(dbo.as[Option[String]]("created_at")),
        day_of_week = dbo.as[Option[String]]("day_of_week"),
        duration = dbo.as[Int]("duration"),
        entry_page = dbo.as[Option[String]]("entry_page"),
        entry_url = dbo.as[Option[String]]("entry_url"),
        exit_url = dbo.as[Option[String]]("exit_url"),
        last_activity = strOptToDtOpt(dbo.as[Option[String]]("last_activity")),
        local_hour = dbo.as[Option[Int]]("local_hour"),
        page_views = dbo.as[Option[Int]]("page_views"),
        revenue = dbo.as[Option[Double]]("revenue")
      ),
      form = ArrivalFactForm(
        email = dbo.as[Option[String]]("email"),
        form_city = dbo.as[Option[String]]("form_city"),
        form_state = dbo.as[Option[String]]("form_state"),
        form_zip = dbo.as[Option[String]]("form_zip"),
        electric_bill = dbo.as[Option[String]]("electric_bill"),
        prop_own = dbo.as[Option[String]]("prop_own")
      ),
      event_1 = ArrivalFactEvent1(
        maxmind_failure_on_page_load = dbo.as[Int]("maxmind_failure_on_page_load"),
        landing_page_completed = dbo.as[Int]("landing_page_completed"),
        address_completed = dbo.as[Int]("address_completed"),
        ownership_completed = dbo.as[Int]("ownership_completed"),
        power_bill_completed = dbo.as[Int]("power_bill_completed"),
        power_company_completed = dbo.as[Int]("power_company_completed"),
        name_completed = dbo.as[Int]("name_completed"),
        email_completed = dbo.as[Int]("email_completed"),
        phone_completed = dbo.as[Int]("phone_completed"),
        email_modal_completed = dbo.as[Int]("email_modal_completed"),
        credit_score_completed = dbo.as[Int]("credit_score_completed"),
        creative = dbo.as[Option[String]]("creative"),
        page_focus = dbo.as[Int]("page_focus"),
        page_blur = dbo.as[Int]("page_blur"),
        event_category = dbo.as[Option[String]]("event_category"),
        events_count = dbo.as[Int]("events_count"),
        form_step_1 = dbo.as[Int]("form_step_1"),
        form_step_2 = dbo.as[Int]("form_step_2"),
        form_step_3 = dbo.as[Int]("form_step_3"),
        form_step_2b = dbo.as[Int]("form_step_2b"),
        page_rendered = dbo.as[Int]("page_rendered"),
        form_step_4 = dbo.as[Int]("form_step_4")
      ),
      event_2 = ArrivalFactEvent2(
        form_step_7 = dbo.as[Int]("form_step_7"),
        form_step_8 = dbo.as[Int]("form_step_8"),
        lp_content_engage = dbo.as[Int]("lp_content_engage"),
        form_complete = dbo.as[Int]("form_complete"),
        page_closed = dbo.as[Int]("page_closed"),
        page_loaded = dbo.as[Int]("page_loaded"),
        form_step_5 = dbo.as[Int]("form_step_5"),
        form_step_6 = dbo.as[Int]("form_step_6")
      ),
      u_event_1 = ArrivalFactUEvent1(
        u_page_closed = dbo.as[Int]("u_page_closed"),
        u_page_loaded = dbo.as[Int]("u_page_loaded"),
        u_form_step_2b = dbo.as[Int]("u_form_step_2b"),
        u_page_rendered =dbo.as[Int]("u_form_rendered"),
        u_form_step_1 = dbo.as[Int]("u_form_step_1"),
        u_form_step_2 = dbo.as[Int]("u_form_step_2"),
        u_form_step_3 = dbo.as[Int]("u_form_step_3"),
        u_form_step_4 = dbo.as[Int]("u_form_step_4"),
        u_form_step_5 = dbo.as[Int]("u_form_step_5"),
        u_maxmind_failure_on_page_load = dbo.as[Int]("u_maxmind_failure_on_page_load"),
        u_landing_page_completed = dbo.as[Int]("u_landing_page_completed"),
        u_address_completed = dbo.as[Int]("u_address_completed"),
        u_ownership_completed = dbo.as[Int]("u_ownership_completed"),
        u_power_bill_completed = dbo.as[Int]("u_power_bill_completed"),
        u_power_company_completed = dbo.as[Int]("u_power_company_completed"),
        u_name_completed = dbo.as[Int]("u_name_completed"),
        u_email_completed = dbo.as[Int]("u_email_completed"),
        u_phone_completed = dbo.as[Int]("u_phone_completed"),
        u_email_modal_completed = dbo.as[Int]("u_email_modal_completed"),
        u_credit_score_completed = dbo.as[Int]("u_credit_score_completed"),
        u_page_focus = dbo.as[Int]("u_page_focus"),
        u_page_blur = dbo.as[Int]("u_page_blur")
      ),
      u_event_2 = ArrivalFactUEvent2(
        u_form_step_6 = dbo.as[Int]("u_form_step_6"),
        u_form_step_7 = dbo.as[Int]("u_form_step_7"),
        u_form_step_8 = dbo.as[Int]("u_form_step_8"),
        u_form_complete = dbo.as[Int]("u_form_complete")
      )
    )
    
    def dtOptToStrOpt(dtOpt: Option[DateTime]): Option[String] = dtOpt match {
      case Some(dt) => Some(dt.toString(dtf))
      case _ => None
    }
  
    def strOptToDtOpt(strOpt: Option[String]): Option[DateTime] = strOpt match {
      case Some(str) => Some(DateTime.parse(str, dtf))
      case _ => None
    }
}